substitutions:
  _GCR_HOSTNAME: gcr.io
  _GCR_REPO: 'python-api-template'
  _IMAGE: 'python-api-template-image'
  _SERVICE: 'python-api-template-service'

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '$_GCR_HOSTNAME/$PROJECT_ID/$_GCR_REPO/$_IMAGE', './api/' ]

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '$_GCR_HOSTNAME/$PROJECT_ID/$_GCR_REPO/$_IMAGE' ]

  # Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$_GCR_REPO/$_IMAGE'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
